[auth]
url = 'https://oauth.vk.com/authorize'
app_id = '7395093'
scope = 'friends,groups,offline'
redirect_uri = 'https://oauth.vk.com/blank.html'
user_agent = 'Mozilla/5.0 (Windows NT 6.1; rv:52.0) Gecko/20100101 Firefox/52.0'